# Building Neural Network from Scratch Part - 10

In [1]:
# Importing libraries
import numpy as np

In [2]:
# Initial inputs
inputs = np.array([1, 2, 3, 4])

# Initial weights and biases
weights = np.array([
    [0.1, 0.2, 0.3, 0.4],
    [0.5, 0.6, 0.7, 0.8],
    [0.9, 1.0, 1.1, 1.2]
])

biases = np.array([0.1, 0.2, 0.3])

# Learning rate
learning_rate = 0.001

In [3]:
# ReLU activation function and its derivative
def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return np.where(x > 0, 1, 0)

### Backpropagation: Layer of Neurons

Note: 
- numpy.outer() function compute the outer product of two vectors. out[i, j] = a[i] * b[j]<br>
- The numpy.one_like() function returns an array of given shape and type as a given array, with ones.

<img src="E:\Building-Neural-Network-from-Scratch\Diagram - 1.jpg">

In [4]:
# Training loop
for iteration in range(200):
    # Forward pass
    z = np.dot(weights, inputs) + biases
    a = relu(z)
    y = np.sum(a)

    # calculate loss
    loss = y ** 2

    # Backward pass
    # Gradient of loss with respect to output y
    dL_dy = 2 * y
    # Gradient of y with respect to a
    dy_da = np.ones_like(a)
    # Gradient of loss with respect to a
    dL_da = dL_dy * dy_da
    # Gradient of a with respect to z (ReLU derivative)
    da_dz = relu_derivative(z)
    # Gradient of loss with respect to z
    dL_dz = dL_da * da_dz

    # Gradient of z with respect to weights and biases
    dL_dW = np.outer(dL_dz, inputs)
    # print(dL_dW)
    dL_db = dL_dz

    # Update weights and biases
    weights -= learning_rate * dL_dW
    biases -= learning_rate * dL_db

    # Print the loss every 20 iterations
    if iteration % 20 == 0:
        print(f"Iteration {iteration}, Loss: {loss}")

# Final weights and biases
print("Final weights:\n", weights)
print("Final biases:\n", biases)

Iteration 0, Loss: 466.56000000000006
Iteration 20, Loss: 5.32959636083938
Iteration 40, Loss: 0.4119152340489983
Iteration 60, Loss: 0.03183621207946751
Iteration 80, Loss: 0.0024605654653895997
Iteration 100, Loss: 0.00019017282566014768
Iteration 120, Loss: 1.4698126966450583e-05
Iteration 140, Loss: 1.1359926717817246e-06
Iteration 160, Loss: 8.77988980016028e-08
Iteration 180, Loss: 6.785824135779993e-09
Final weights:
 [[-0.00698895 -0.01397789 -0.02096684 -0.02795579]
 [ 0.25975286  0.11950572 -0.02074143 -0.16098857]
 [ 0.53548461  0.27096922  0.00645383 -0.25806156]]
Final biases:
 [-0.00698895 -0.04024714 -0.06451539]
