# Building Neural Network from Scratch Part - 6

In [1]:
# Importing Numpy
import numpy as np
from nnfs.datasets import spiral_data
import nnfs
nnfs.init()

### Dense Layer Class

In [2]:
class Layer_Dense:
    # Layer initialization
    def __init__(self, n_inputs, n_neurons):
        # Initialize weights and biases
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    # Forward pass
    def forward(self, batch_inputs):
        # Calculate the output values from inputs, weights and biases
        self.output = np.dot(batch_inputs, self.weights) + self.biases

### **Activation Function: ReLU**

In [3]:
inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]
output = np.maximum(0, inputs)

print(output)

[0.  2.  0.  3.3 0.  1.1 2.2 0. ]


### Building the ReLU Activation Function Class

In [4]:
# ReLU activation
class Activation_ReLU:
    def forward(self, inputs):
        # Calculate the output value from input
        self.output = np.maximum(0, inputs)

### Using ReLU Class in the Spiral Dataset

In [5]:
# Create Dataset
X, Y = spiral_data(samples = 100, classes = 3)

# Create Dense Layer with 2 input features and 3 output values
dense_1 = Layer_Dense(2, 3)
# Perform a forward pass of our training data through this layer
dense_1.forward(X)

# Create ReLU activation (to be used with Dese layer)
activation_1 = Activation_ReLU()
# Forward pass through activation layer, takes an output from previous layer
activation_1.forward(dense_1.output)

# Let's see the output of the first few samples
print(activation_1.output[: 5])

[[0.         0.         0.        ]
 [0.         0.00011395 0.        ]
 [0.         0.00031729 0.        ]
 [0.         0.00052666 0.        ]
 [0.         0.00071401 0.        ]]


### **Activation Function: Softmax**

In [13]:
inputs = [
    [1, 2, 3, 2.5],
    [2.0, 5.0, -1.0, 2],
    [-1.5, 2.7, 3.3, -0.8]
]

# Compute exponentials in a numerically stable way
# Subtracting the maximum value in each input row to prevent large exponentials (improves numerical stability)
exp_values = np.exp(inputs - np.max(inputs, axis = 1, keepdims = True))

# Normalize the exponentials to get probabilities (softmax function)
# Divide each element by the sum of exponentials in its row
probabilities = exp_values / np.sum(exp_values, axis = 1, keepdims = True)

# Print the resulting probabilities for each input vector
print(probabilities)

[[0.06414769 0.17437149 0.47399085 0.28748998]
 [0.04517666 0.90739747 0.00224921 0.04517666]
 [0.00522984 0.34875873 0.63547983 0.0105316 ]]


In [ ]:
# Sum the probabilities across each row (i.e., for each input sample)
# Since we applied softmax, each row represents a probability distribution
# So, the sum of each row should be approximately 1.0

np.sum(probabilities, axis = 1)

array([1., 1., 1.])

### Building the Softmax Activation Function Class

In [8]:
# Softmax activation
class Activation_Softmax:
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis = 1, keepdims = True))
        probabilities = exp_values / np.sum(exp_values, axis = 1, keepdims = True)
        
        # Assigning the probability values into output
        self.output = probabilities

### One Forward Pass (Without Loss Function)

Note: In our neural network, we use ReLU activation in all the hidden layers to add non-linearity. But in the output layer, we use the Softmax activation function for multi-class classification. Softmax converts the outputs into probabilities that add up to 1, making it easier to identify the predicted class.

In [9]:
# Create Dataset
X, Y = spiral_data(samples = 100, classes = 3)

# Create Dense Layer with 2 input features and 3 output values
dense_1 = Layer_Dense(2, 3)
# Create ReLU activation (to be used with Dese layer)
activation_1 = Activation_ReLU()

# Create a second Dense layer with 3 input features (as we take output of previous layer here) and 3 output values
dense_2 = Layer_Dense(3, 3)
# Create Softmax activation (to be used with Dese layer)
activation_2 = Activation_Softmax()


# Make a forward pass of our training data through this layer
dense_1.forward(X)
# Make a forward pass through activation function, it takes the output of first dense layer
activation_1.forward(dense_1.output)
# Make a forward pass through second dense layer, it takes outputs of activation function of first layer as inputs
dense_2.forward(activation_1.output)
# Make a forward pass through activation function, it takes the output of second dense layer
activation_2.forward(dense_2.output)

# Let's see the output of the first few samples
print(activation_2.output[: 5])

[[0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]]
