# **Building Neural Network from Scratch Part - 3**

In [1]:
# Importing Numpy
import numpy as np

### Coding only One Layer

In [2]:
batch_inputs = [
    [1.0, 2.0, 3.0, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]
]

weights = [
    [0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]

biases = [2.0, 3.0, 0.5]

# Convert each Python Lists into the Numpy Arrays
inputs = np.array(batch_inputs)
weights = np.array(weights)
biases = np.array(biases)

# Calculate the dot product and add the bias terms
first_layer_output = np.dot(inputs, weights.T) + biases

print(first_layer_output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


### Two Layers and Batch of Data Using Numpy

In [3]:
batch_inputs = [
    [1.0, 2.0, 3.0, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]
]

weights_1 = [
    [0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]]

biases_1 = [2.0, 3.0, 0.5]

weights_2 = [
    [0.1, -0.14, 0.5],
    [-0.5, 0.12, -0.33],
    [-0.44, 0.73, -0.13]
]

biases_2 = [-1, 2, -0.5]

# Convert each Python Lists into the Numpy Arrays
inputs = np.array(batch_inputs)
weights_1 = np.array(weights_1)
biases_1 = np.array(biases_1)
weights_2 = np.array(weights_2)
biases_2 = np.array(biases_2)

# Calculate the output of the First Layer
layer_1_outputs = np.dot(inputs, weights_1.T) + biases_1

# Calculate the output of the Second Layer
layer_2_outputs = np.dot(layer_1_outputs, weights_2.T) + biases_2

print(layer_2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]
