# Building Neural Network from Scratch Part - 10

In [1]:
# Importing libraries
import numpy as np

In [2]:
# Initial inputs
inputs = np.array([1, 2, 3, 4])

# Initial weights and biases
weights = np.array([
    [0.1, 0.2, 0.3, 0.4],
    [0.5, 0.6, 0.7, 0.8],
    [0.9, 1.0, 1.1, 1.2]
])

biases = np.array([0.1, 0.2, 0.3])

# Learning rate
learning_rate = 0.001

In [3]:
# ReLU activation function and its derivative
def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return np.where(x > 0, 1, 0)

### Backpropagation: Layer of Neurons

Note: 
- numpy.outer() function compute the outer product of two vectors. out[i, j] = a[i] * b[j]<br>
- The numpy.one_like() function returns an array of given shape and type as a given array, with ones.

In [5]:
# Training loop
for iteration in range(200):
    # Forward pass
    z = np.dot(weights, inputs) + biases
    a = relu(z)
    y = np.sum(a)

    # calculate loss
    loss = y ** 2

    # Backward pass
    # Gradient of loss with respect to output y
    dL_dy = 2 * y
    # Gradient of y with respect to a
    dy_da = np.ones_like(a)
    # Gradient of loss with respect to a
    dL_da = dL_dy * dy_da
    # Gradient of a with respect to z (ReLU derivative)
    da_dz = relu_derivative(z)
    # Gradient of loss with respect to z
    dL_dz = dL_da * da_dz

    # Gradient of z with respect to weights and biases
    dL_dW = np.outer(dL_dz, inputs)
    # print(dL_dW)
    dL_db = dL_dz

    # Update weights and biases
    weights -= learning_rate * dL_dW
    biases -= learning_rate * dL_db

    # Print the loss every 20 iterations
    if iteration % 20 == 0:
        print(f"Iteration {iteration}, Loss: {loss}")

# Final weights and biases
print("Final weights:\n", weights)
print("Final biases:\n", biases)

[0.00000000e+00 0.00000000e+00 4.58023819e-05] 
 [1 2 3 4]
Iteration 0, Loss: 5.244645462652863e-10
[0.00000000e+00 0.00000000e+00 4.29626342e-05] 
 [1 2 3 4]
[0.00000000e+00 0.00000000e+00 4.02989509e-05] 
 [1 2 3 4]
[0.00000000e+00 0.00000000e+00 3.78004159e-05] 
 [1 2 3 4]
[0.00000000e+00 0.00000000e+00 3.54567901e-05] 
 [1 2 3 4]
[0.00000000e+00 0.00000000e+00 3.32584691e-05] 
 [1 2 3 4]
[0.00000000e+00 0.00000000e+00 3.11964441e-05] 
 [1 2 3 4]
[0.00000000e+00 0.00000000e+00 2.92622645e-05] 
 [1 2 3 4]
[0.00000000e+00 0.00000000e+00 2.74480041e-05] 
 [1 2 3 4]
[0.00000000e+00 0.00000000e+00 2.57462279e-05] 
 [1 2 3 4]
[0.00000000e+00 0.00000000e+00 2.41499617e-05] 
 [1 2 3 4]
[0.00000000e+00 0.00000000e+00 2.26526641e-05] 
 [1 2 3 4]
[0.00000000e+00 0.00000000e+00 2.12481989e-05] 
 [1 2 3 4]
[0.00000000e+00 0.00000000e+00 1.99308106e-05] 
 [1 2 3 4]
[0.00000000e+00 0.00000000e+00 1.86951003e-05] 
 [1 2 3 4]
[0.00000000e+00 0.00000000e+00 1.75360041e-05] 
 [1 2 3 4]
[0.00000000e+00