# **Building Neural Network from Scratch Part - 2**

In [1]:
# Importing Numpy
import numpy as np

### Single Neuron Using Numpy

Note: In case of vector-vector dot product, np.dot(a, b) = np.dot(b, a)

In [2]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

output = np.dot(inputs, weights) + bias
# output = np.dot(weights, inputs) + bias    # Both the statement will act same

print(output)

4.8


### Layer of Neurons Using Numpy

Note: A dot product of a Metrix and a Vector results in a list of dot products.
The np.dot() method treats the metrix as a list of vectors and performs a dot product of each of those vectors with the other vector

In [3]:
inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
          [0.5, -0.91, 0.26, -0.5],
          [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

layer_output = np.dot(weights, inputs) + biases
# test_layer_output_1 = np.dot(inputs, weights) + biases    # It throws an error because of the dimension mismatch
# test_layer_output_2 = np.dot(inputs, np.transpose(weights)) + biases


print(layer_output)
# print(test_layer_output_2)

[4.8   1.21  2.385]


### Layer of Neurons and Batch of Data Using Numpy

Note: We can't transpose lists in Python, so we have to convert the weight matrix into an Array first

In [4]:
batch_inputs = [[1.0, 2.0, 3.0, 2.5],
                [2.0, 5.0, -1.0, 2.0],
                [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1],
          [0.5, -0.91, 0.26, -0.5],
          [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

outputs = np.dot(batch_inputs, np.array(weights).T) + biases

print(outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
