# **Building Neural Network from Scratch Part - 5**

In [1]:
# Importing Numpy
import numpy as np

### Sum of array elements over a given axis

In [2]:
Arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Total sum of all elements, adds every element in the matrix
print(np.sum(Arr))
# Axis = None means “flatten everything” and then sum
print(np.sum(Arr, axis = None))
# Sum along axis 0 (columns), adds down each column
print(np.sum(Arr, axis = 0))
print(np.sum(Arr, axis = 0).shape)
# Sum along axis 1 (rows), adds down each row
print(np.sum(Arr, axis = 1))
print(np.sum(Arr, axis = 1).shape)

45
45
[12 15 18]
(3,)
[ 6 15 24]
(3,)


### Use of keepdims

Note: If this is set to True, the axes which are reduced are left in the result as dimensions with size one. With this option, the result will broadcast correctly against the input array.

In [3]:
print(np.sum(Arr, axis = 0, keepdims = True))
print(np.sum(Arr, axis = 0, keepdims = True).shape)

print(np.sum(Arr, axis = 1, keepdims = True))
print(np.sum(Arr, axis = 1, keepdims = True).shape)

print(np.max(Arr, axis = 0))
print(np.max(Arr, axis = 1))

[[12 15 18]]
(1, 3)
[[ 6]
 [15]
 [24]]
(3, 1)
[7 8 9]
[3 6 9]


### Broadcasting Rule

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimension and works its way left. Two dimensions are compatible when<br>
- they are equal, or
- one of them is 1.

When either of the dimensions compared is one, the other is used. In other words, dimensions with size 1 are stretched or “copied” to match the other.

In [4]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])  # Dim: 3 x 3

# This 3 x 1 matrix will be broadcasted columnwise into 3 x 3 matrix
B = np.array([
    [1],
    [2],
    [3]
])  # Dim: 3 x 1

print(A + B)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [5]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])  # Dim: 3 x 3

# This 1 x 3 matrix will be broadcasted columnwise into 3 x 3 matrix
B = np.array([[1, 2, 3]])  # Dim: 1 x 3

print(A + B)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [6]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.max(A, axis = 1)
print(B)   # Dim is treated as: 1 x 3
print(B.shape)

# This is not what we want
print(A - B)

print("\n\n")

C = np.max(A, axis = 1, keepdims = True)
print(C)   # Dim: 3 x 1
print(C.shape)

# This is the correct answer
print(A - B)

[3 6 9]
(3,)
[[-2 -4 -6]
 [ 1 -1 -3]
 [ 4  2  0]]



[[3]
 [6]
 [9]]
(3, 1)
[[-2 -4 -6]
 [ 1 -1 -3]
 [ 4  2  0]]
